### ISSUE TITLE
Transformar tabela tb_chart em view materializada

### ISSUE THREAD

**Issue by Malnati** [milleniumbrasil/isagro-indicadores-api#1]
Durante a reunião entre Carlos Eduardo Miranda Mota e Ricardo Malnati, discutimos sobre a necessidade de transformar a tabela desnormalizada TB_chart em uma estrutura que suporte as necessidades dos geosserviços. A solução proposta é a criação de uma view materializada, que irá facilitar a manipulação dos dados e a integração com geosserviços.

Detalhes:

- A tabela TB_chart contém informações desnormalizadas que precisam ser otimizadas para consultas e manipulações mais eficientes.
- A criação de uma view materializada permitirá a manipulação de dados espaciais e agregará performance para as operações de leitura e consulta que serão realizadas nos geosserviços.

Esperado:

1. Definir a estrutura da view materializada com base nos dados presentes na tabela TB_chart.
2. Criar a view materializada considerando as futuras operações espaciais que serão aplicadas.
3. Testar a integridade dos dados na nova view para garantir que as informações permaneçam consistentes e otimizadas.
4. Integrar a nova view materializada com os serviços de geosserviços e realizar ajustes conforme necessário.

**Comment by cmotadev** [comment]
A tabela original tb_chart foi substituída por uma view materializada (MatView), resultante de combinações de consultas:
- Criação de séries de dados derivados de operações (Balanço de NPK, Recálculo de GEE para CO2e) através de funções específicas
- Agregação dos indicadores para calcular a soma pelo país (futuramente região) - Para usar os dados totais do país, o campo "state" precisa ser definido com NULL, e o "país" como BR

Para aumentar o leque de operações e/ou agregações, basta criar as funções, se necessário, e chamá-las dentro da MatView.

OBS: As funções precisam retornar os mesmos campos da MatView
